export const gradients = [
  {
    id: "aurora-dream",
    name: "Aurora Dream",
    colors: ["#5B00FF", "#00D4FF", "#62FFAE"],
    tags: ["cool", "night", "neon"],
    popularity: 96,
    material: "glass",
    primaryHue: "blue",
    colorCount: 3,
    description: "Vibrant aurora-inspired gradient with electric blues and greens.",
    related: ["sunset-pop", "citrus-muse"],
  },
  {
    id: "sunset-pop",
    name: "Sunset Pop",
    colors: ["#FF6B6B", "#FFD93D"],
    tags: ["warm", "sunset", "bold"],
    popularity: 88,
    material: "fabric",
    primaryHue: "orange",
    colorCount: 2,
    description: "Radiant sunset gradient with optimistic warmth.",
    related: ["aurora-dream", "terra-firma"],
  },
  {
    id: "terra-firma",
    name: "Terra Firma",
    colors: ["#2F4858", "#F6AE2D", "#F26419"],
    tags: ["earthy", "organic", "grounded"],
    popularity: 75,
    material: "matte",
    primaryHue: "brown",
    colorCount: 3,
    description: "Earth-inspired palette balancing deep teal and warm clay.",
    related: ["forest-breathe", "sunset-pop"],
  },
  {
    id: "forest-breathe",
    name: "Forest Breathe",
    colors: ["#0B3954", "#087E8B", "#BFD7EA"],
    tags: ["calm", "nature", "fresh"],
    popularity: 82,
    material: "satin",
    primaryHue: "green",
    colorCount: 3,
    description: "Cooling forest tones with a misty highlight.",
    related: ["aurora-dream", "midnight-oil"],
  },
  {
    id: "midnight-oil",
    name: "Midnight Oil",
    colors: ["#191716", "#2D3047", "#44BBA4"],
    tags: ["moody", "sleek", "futuristic"],
    popularity: 90,
    material: "metal",
    primaryHue: "teal",
    colorCount: 3,
    description: "High-contrast gradient with modern teal lighting.",
    related: ["aurora-dream", "lilac-haze"],
  },
  {
    id: "lilac-haze",
    name: "Lilac Haze",
    colors: ["#E0AAFF", "#C77DFF", "#9D4EDD"],
    tags: ["soft", "dreamy", "feminine"],
    popularity: 85,
    material: "silk",
    primaryHue: "purple",
    colorCount: 3,
    description: "Delicate lilac shades drifting into vibrant violet.",
    related: ["aurora-dream", "sunrise-mist"],
  },
  {
    id: "sunrise-mist",
    name: "Sunrise Mist",
    colors: ["#FAD0C4", "#FFD1FF"],
    tags: ["airy", "pastel", "gentle"],
    popularity: 79,
    material: "velvet",
    primaryHue: "pink",
    colorCount: 2,
    description: "Soft pastel blend capturing daybreak light.",
    related: ["lilac-haze", "citrus-muse"],
  },
  {
    id: "citrus-muse",
    name: "Citrus Muse",
    colors: ["#F9ED69", "#F08A5D", "#B83B5E"],
    tags: ["energetic", "tropical", "playful"],
    popularity: 92,
    material: "plastic",
    primaryHue: "yellow",
    colorCount: 3,
    description: "Juicy citrus gradient with playful contrast.",
    related: ["sunset-pop", "terra-firma"],
  },
  {
    id: "oceanic",
    name: "Oceanic",
    colors: ["#2193b0", "#6dd5ed"],
    tags: ["calm", "aqua", "serene"],
    popularity: 70,
    material: "glass",
    primaryHue: "blue",
    colorCount: 2,
    description: "Refreshing aquatic blues ideal for airy layouts.",
    related: ["forest-breathe", "aurora-dream"],
  },
  {
    id: "ember-glow",
    name: "Ember Glow",
    colors: ["#e96443", "#904e95"],
    tags: ["warm", "moody", "sunset"],
    popularity: 83,
    material: "metal",
    primaryHue: "red",
    colorCount: 2,
    description: "Smoky ember-inspired gradient with subtle drama.",
    related: ["sunset-pop", "terra-firma"],
  }
];

export const hues = [
  "all",
  "blue",
  "orange",
  "brown",
  "green",
  "teal",
  "purple",
  "pink",
  "yellow",
  "red"
];
